In [13]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('./vgg_model_98.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('./harr_cascade.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.1, 3)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Aaryan'
        if(pred[0][1]>0.5):
            name='Arihant'
        if(pred[0][2]>0.5):
            name='Asmita'
        if(pred[0][3]>0.5):
            name='Jay'
        if(pred[0][4]>0.5):
            name='Vijay'       
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

<>:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\JARVIS\AppData\Local\Temp\ipykernel_26984\1033412184.py:24: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


1/1 [==============================] - 0s 458ms/step
[[0.07890141 0.88584644 0.01189984 0.00194278 0.02140958]]
1/1 [==============================] - 0s 249ms/step
[[0.2400581  0.7060836  0.02754936 0.00690187 0.01940716]]
1/1 [==============================] - 0s 246ms/step
[[0.10129235 0.8706863  0.00630173 0.00334951 0.0183701 ]]
1/1 [==============================] - 0s 249ms/step
[[0.07017042 0.8894057  0.01177898 0.00410824 0.02453667]]
1/1 [==============================] - 0s 282ms/step
[[0.64571446 0.14119591 0.01030301 0.00117583 0.20161082]]
1/1 [==============================] - 0s 245ms/step
[[0.17722434 0.8019271  0.00520655 0.00235995 0.01328205]]
1/1 [==============================] - 0s 276ms/step
[[0.15055816 0.5814677  0.00966929 0.0131636  0.2451413 ]]
1/1 [==============================] - 0s 248ms/step
[[0.14857352 0.7412254  0.07069216 0.00999517 0.02951383]]
1/1 [==============================] - 0s 271ms/step
[[0.070303   0.8675785  0.02601923 0.00497777 0.031